FROM python:3.11.3-alpine3.16

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1



COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir

COPY ./config ./config
COPY ./rabbitmq ./rabbitmq
COPY ./apps/vk_api ./apps/vk_api
COPY ./apps/base ./apps/base
COPY ./main_sender.py .
COPY ./.env .
COPY ./config.yml .
