FROM python:3.11.3-alpine3.16

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1



COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir

COPY ./config .
COPY ./rabbitmq .
COPY ./db .
COPY ./apps/game .
COPY ./apps/bot .
