"""final migration

Revision ID: 15e3ba519523
Revises: 
Create Date: 2023-04-10 17:13:22.440766

"""
from hashlib import sha256

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e3ba519523'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    admins = op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'last_name', name='_name_lastname_uc'),
    sa.UniqueConstraint('vk_id')
    )
    questions = op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('blitz', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    answers = op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('wait_status', sa.String(), nullable=False),
    sa.Column('wait_time', sa.Integer(), nullable=False),
    sa.Column('my_points', sa.Integer(), nullable=False),
    sa.Column('players_points', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('blitz_round', sa.Integer(), nullable=False),
    sa.Column('current_question_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_captains',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('game_score',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('game_speakers',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('used_questions',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'question_id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(admins,
                   [
                       {
                           "id": 1,
                           "email": "admin@admin.com",
                           "password": sha256("admin".encode()).hexdigest()
                       }
                   ]
                   )
    op.bulk_insert(questions,
                   [
                       {
                           "id": "ae4ca5ab-f5e0-48fc-9a1b-6b1ae8856af1",
                           "blitz": False,
                           "text": "Какого числа какого месяца в РФ празднуется день программиста (в невисокосный год)?"
                       },
                       {
                           "id": "9bd4f933-5a58-4daf-a1d5-feb236e0ec20",
                           "blitz": False,
                           "text": "Какой термин, относящийся к процессу разработки программного обеспечения, появился благодаря коммодору ВМФ США Грейс Хоппер?"
                       },
                       {
                           "id": "3f563f31-1a6b-4db6-b907-6333fed238b3",
                           "blitz": False,
                           "text": "Как называлось то, что 'разгадал' Алан Тьюринг?"
                       },
                       {
                           "id": "f8936956-1459-4ba0-a6c1-9d4b94250f96",
                           "blitz": False,
                           "text": "Из какого материала раньше изготавливались шестерёнки, используемые в конструкциях подводных лодок, для ограничения шума?"
                       },
                       {
                           "id": "66a5c9fc-7a62-4129-9022-d57c2f6e73c5",
                           "blitz": False,
                           "text": "Назовите фамилию российского писателя, который написал три произведения, названия которых начинаются на букву 'О'?"
                       },
                       {
                           "id": "eb1c295d-2349-409f-a82d-ea7df842922c",
                           "blitz": False,
                           "text": "Сколько раз ходил к морю старик из сказки А.С. Пушкина 'О рыбаке и рыбке'?"
                       },
                       {
                           "id": "dc9fec6f-359f-4079-8b8b-47aada6b71cc",
                           "blitz": False,
                           "text": "Назовите одно из главных изобретений Архимеда, без которого автомобилисты не рускнут отправиться в дальнюю поездку?"
                       },
                       {
                           "id": "84140392-164f-4cfd-a5c2-297ecab3aa90",
                           "blitz": False,
                           "text": "Какое приблизительно расстояние между Царьградом и Константинополем?"
                       },
                       {
                           "id": "f4889ab3-6ec8-49f1-ba92-58359d66fa5e",
                           "blitz": False,
                           "text": "Кто использовал в своей работе термин 'ревущие сороковые'?"
                       },
                       {
                           "id": "b6097ec6-b7e6-4cf1-b87e-dd61153258cb",
                           "blitz": False,
                           "text": "Какая птица способна летать как головой так и хвостом вперёд?"
                       },
                       {
                           "id": "5343f8df-28eb-4fb7-9575-aa071f8314ff",
                           "blitz": False,
                           "text": "Какое самое известное прозвище Нью-Йорка?"
                       },
                       {
                           "id": "60156044-6f30-48c4-9058-4c48c7e2d0c7",
                           "blitz": True,
                           "text": "Назовите столицу Австралии"
                       },
                       {
                           "id": "2fe360bb-8c38-448d-a2f3-7cceb7ecfa85",
                           "blitz": True,
                           "text": "Назовите столицу Турции"
                       },
                       {
                           "id": "166780b2-6711-47f3-b6da-d2b14ee6d609",
                           "blitz": False,
                           "text": "Кому посвящён памятник, на пьедестале которого высечено: 'Он остановил Солнце и сдвинул Землю'?"
                       },
                       {
                           "id": "7c54faf0-5806-4a6f-b08f-bccc32e8be75",
                           "blitz": True,
                           "text": "Назовите имя доктора Ватсона из серии рассказов о Шерлоке Холмсе А.К. Дойла"
                       },
                       {
                           "id": "08d546e9-cb89-48c8-96b3-d7517d4f10bf",
                           "blitz": True,
                           "text": "Назовите то, во что по мнению А. Эйнштейна не играет бог."
                       },
                       {
                           "id": "38755672-27d2-4924-b8af-dc0976b415b1",
                           "blitz": True,
                           "text": "Какого химического элемента из перечисленных не существует? Германий, рутений, франций, австрий, нихоний"
                       },
                       {
                           "id": "d8366638-1df9-467d-b7ee-195ab15aec03",
                           "blitz": True,
                           "text": "В средние века каждый рецепт начинался со слова 'возьмите'. А как будет на латыне 'возьмите'?"
                       },
                       {
                           "id": "5dc86ca8-94f9-4321-b5f1-b0dfe61af2d9",
                           "blitz": True,
                           "text": "Назовите фамилию американского политика, изображённого на купюре в 100 долларов."
                       }
                   ]

                   )
    op.bulk_insert(
        answers,
        [
            {
                "id": "32b576d0-661f-4935-a30e-2b7f61cd1a8e",
                "text": "13 сентября|13сентября|13.09|13 09",
                "question_id": "ae4ca5ab-f5e0-48fc-9a1b-6b1ae8856af1"
            },
            {
                "id": "a75afccd-485c-4d3d-a10c-356ab3089bcc",
                "text": "дебаг|debugging",
                "question_id": "9bd4f933-5a58-4daf-a1d5-feb236e0ec20"
            },
            {
                "id": "9c4dba94-dd84-4a77-91cd-b02e567d175a",
                "text": "энигма",
                "question_id": "3f563f31-1a6b-4db6-b907-6333fed238b3"
            },
            {
                "id": "563e8f3d-dff3-495e-a599-79b415d344ad",
                "text": "дерево",
                "question_id": "f8936956-1459-4ba0-a6c1-9d4b94250f96"
            },
            {
                "id": "f615207f-a647-4bc0-ab18-cfa07f76edb5",
                "text": "гончаров",
                "question_id": "66a5c9fc-7a62-4129-9022-d57c2f6e73c5"
            },
            {
                "id": "de85a367-2666-4800-8dc6-487925b058ef",
                "text": "6",
                "question_id": "eb1c295d-2349-409f-a82d-ea7df842922c"
            },
            {
                "id": "7224e7b9-5e68-457a-b817-1645b400f371",
                "text": "домкрат",
                "question_id": "dc9fec6f-359f-4079-8b8b-47aada6b71cc"
            },
            {
                "id": "cfc2f7ac-4a5d-4c24-b7a1-25f33e1c9096",
                "text": "0|ноль",
                "question_id": "84140392-164f-4cfd-a5c2-297ecab3aa90"
            },
            {
                "id": "4fd21e41-4559-4821-9210-fa0c777eea9a",
                "text": "моряки|моряк|путешественники|путешественник",
                "question_id": "f4889ab3-6ec8-49f1-ba92-58359d66fa5e"
            },
            {
                "id": "76bea052-0f2c-4653-a1d4-5215b84f5b50",
                "text": "колибри",
                "question_id": "b6097ec6-b7e6-4cf1-b87e-dd61153258cb"
            },
            {
                "id": "094c59de-b706-4880-aeb4-d001c91e686e",
                "text": "большое яблоко",
                "question_id": "5343f8df-28eb-4fb7-9575-aa071f8314ff"
            },
            {
                "id": "4ce64a3b-efc6-4f87-b085-b4ffa75d6374",
                "text": "канберра",
                "question_id": "60156044-6f30-48c4-9058-4c48c7e2d0c7"
            },
            {
                "id": "6d28f667-e2a2-49d4-ad6d-18a7c4da8d5f",
                "text": "анкара",
                "question_id": "2fe360bb-8c38-448d-a2f3-7cceb7ecfa85"
            },
            {
                "id": "7f35604e-e19a-4162-84a1-21bd5cd38dda",
                "text": "коперник",
                "question_id": "166780b2-6711-47f3-b6da-d2b14ee6d609"
            },
            {
                "id": "42fa7601-57e0-4f69-b5ed-39d281514857",
                "text": "джон",
                "question_id": "7c54faf0-5806-4a6f-b08f-bccc32e8be75"
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_questions')
    op.drop_table('game_speakers')
    op.drop_table('game_score')
    op.drop_table('game_captains')
    op.drop_table('games')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('players')
    op.drop_table('admins')
    # ### end Alembic commands ###
