"""game.status added

Revision ID: 29613b47d875
Revises: fefeb335feed
Create Date: 2023-03-27 22:50:20.646711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29613b47d875'
down_revision = 'fefeb335feed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
