"""current_question added

Revision ID: 41ca513e05bd
Revises: 470837b0ef0f
Create Date: 2023-04-01 00:14:29.833586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ca513e05bd'
down_revision = '470837b0ef0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('current_question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'questions', ['current_question_id'], ['id'])
    op.create_unique_constraint(None, 'questions', ['text'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'current_question_id')
    # ### end Alembic commands ###
