"""wait_time added

Revision ID: 470837b0ef0f
Revises: 4a13e0dab4be
Create Date: 2023-03-30 12:21:14.620357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470837b0ef0f'
down_revision = '4a13e0dab4be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('wait_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'wait_time')
    # ### end Alembic commands ###
