"""statuses and points added

Revision ID: 4c034dc86039
Revises: eddd6ae899ca
Create Date: 2023-03-28 16:35:46.713595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c034dc86039'
down_revision = 'eddd6ae899ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('wait_status', sa.String(), nullable=False))
    op.add_column('games', sa.Column('my_points', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('players_points', sa.Integer(), nullable=False))
    op.drop_constraint('games_chat_id_key', 'games', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('games_chat_id_key', 'games', ['chat_id'])
    op.drop_column('games', 'players_points')
    op.drop_column('games', 'my_points')
    op.drop_column('games', 'wait_status')
    # ### end Alembic commands ###
