"""questions and answers added

Revision ID: c45a473c51d0
Revises: 4c034dc86039
Create Date: 2023-03-29 11:34:22.637237

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c45a473c51d0'
down_revision = '4c034dc86039'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    questions = op.create_table('questions',
                                sa.Column('id', sa.Integer(), nullable=False),
                                sa.Column('text', sa.String(), nullable=False),
                                sa.PrimaryKeyConstraint('id')
                                )
    answers = op.create_table('answers',
                              sa.Column('id', sa.Integer(), nullable=False),
                              sa.Column('text', sa.String(), nullable=False),
                              sa.Column('question_id', sa.Integer(), nullable=True),
                              sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
                              sa.PrimaryKeyConstraint('id')
                              )
    op.create_table('used_questions',
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('game_id', 'question_id')
                    )
    # ### end Alembic commands ###
    op.bulk_insert(questions,
                   [
                       {
                           "id": 7,
                           "text": "Какого числа какого месяца в РФ празднуется день программиста (в невисокосный год)?"
                       },
                       {
                           "id": 8,
                           "text": "Какой термин, относящийся к процессу разработки программного обеспечения, появился благодаря коммодору ВМФ США Грейс Хоппер?"
                       },
                       {
                           "id": 9,
                           "text": "Как называлось то, что 'разгадал' Алан Тьюринг?"
                       },
                       {
                           "id": 10,
                           "text": "Из какого материала раньше изготавливались шестерёнки, используемые в конструкциях подводных лодок, для ограничения шума?"
                       },
                       {
                           "id": 11,
                           "text": "Назовите фамилию российского писателя, который написал три произведения, названия которых начинаются на букву 'О'?"
                       },
                       {
                           "id": 12,
                           "text": "Сколько раз ходил к морю старик из сказки А.С. Пушкина 'О рыбаке и рыбке'?"
                       },
                       {
                           "id": 13,
                           "text": "Назовите одно из главных изобретений Архимеда, без которого автомобилисты не рускнут отправиться в дальнюю поездку?"
                       },
                       {
                           "id": 14,
                           "text": "Какое приблизительно расстояние между Царьградом и Константинополем?"
                       },
                       {
                           "id": 15,
                           "text": "Кто использовал в своей работе термин 'ревущие сороковые'?"
                       },
                       {
                           "id": 16,
                           "text": "Птица, способная летать как головой так и хвостом вперёд"
                       }
                   ]

                   )
    op.bulk_insert(
        answers,
        [
            {
                "question_id": 7,
                "id": 7,
                "text": "13 сентября|13сентября|13.09|13 09"
            },
            {
                "question_id": 8,
                "id": 8,
                "text": "дебаг|debugging"
            },
            {
                "question_id": 9,
                "id": 9,
                "text": "Энигма"
            },
            {
                "question_id": 10,
                "id": 10,
                "text": "Дерево"
            },
            {
                "question_id": 11,
                "id": 11,
                "text": "Гончаров"
            },
            {
                "question_id": 12,
                "id": 12,
                "text": "6|шесть"
            },
            {
                "question_id": 13,
                "id": 13,
                "text": "Домкрат"
            },
            {
                "question_id": 14,
                "id": 14,
                "text": "0|Ноль"
            },
            {
                "question_id": 15,
                "id": 15,
                "text": "Моряки|Моряк|Путешественники|Путешественник"
            },
            {
                "question_id": 16,
                "id": 16,
                "text": "колибри"
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_questions')
    op.drop_table('answers')
    op.drop_table('questions')
    # ### end Alembic commands ###
