"""game.status added

Revision ID: eddd6ae899ca
Revises: 29613b47d875
Create Date: 2023-03-27 23:00:08.457949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddd6ae899ca'
down_revision = '29613b47d875'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
